### ISSUE TITLE
Avoid naming/registering (a single) runtime gen_server

### ISSUE THREAD

**Issue by zampino** [joergen7/cuneiform#46]
In the current implementation a single GenServer `:cf_cre` is started and registered with name `:cre` 
for each *.cf-file execution or starting the shell mode.

In case we'd want to call `reduce/4` directly (say in building a cuneiform interpreter),
would be probably useful to start a runtime process right there because the same vm
could possibly run multiple cuneiform programs at once, but at present, wouldn't be able to start
different `:cre`s because of the registered name for the process. 

Imagine we would move `cf_sup:start_cre( Mod, ModArg, LibMap )` from [here](https://github.com/joergen7/cuneiform/blob/master/src/cuneiform.erl#L90)

to inside [`reduce/4`](https://github.com/joergen7/cuneiform/blob/master/src/cuneiform.erl#L113) to become something like: 

```erlang
reduce( X0, Rho, Gamma, Cwd, PlatformArguments ) ->
  {ok, RuntimePid} = apply( cf_sup, start_cre, PlatformArguments ),
  Mu = fun( A ) -> cf_cre:submit( RuntimePid, A, Cwd ) end,
  reduce( X0, {Rho, Mu, Gamma, #{}}, Cwd ).
```
Here `cf_cre` would need to implement a `submit/3` and not to register a `{local, cre}` name
in its `start_link` client api.

This would imply that need to pass the runtime module arguments to `reduce` as well, i.e. in the snippet above:

```erlang
[Mod, ModArg, LibMap] = PlatformArguments
```

I realize this fits a very specific use case, but it's maybe worth some discussion :-) .

Looking forward to hearing some comments on this...

**Comment by zampino** [comment]
If we want to see this as a "feature request" it would limit to _exporting cuneiform:reduce/3_ :-) 
but in the _dev_ branch there is some usage of the `:cre` process name a.o. [here](https://github.com/joergen7/cuneiform/blob/dev/src/cf_cre.erl#L272)

which could be avoided with closing the caller Pid inside the [stage application function](https://github.com/joergen7/cuneiform/blob/dev/src/cf_cre.erl#L165)

**Comment by zampino** [comment]
Or a low-impact compromise like this (for them mom) private pull request: 
https://github.com/zampino/cuneiform/pull/1/files

@joergen7 if the case I can publish it to the cuneiform repo

**Comment by zampino** [comment]
this will give maximal freedom to start a cf runtime where/however we want;
say for an interpreter which groups executions based on team / user,  in order to re-use the same
future-cache store of the runtime.

**Comment by zampino** [comment]
mhm, my suggestion in the first comment above with a `reduce/5` with `PlatformArguments` is therefore not ideal

**Comment by joergen7** [comment]
Hey, thx for the suggestions. Please excuse my late answer.

I agree, that the binding of the CRE to a registered service name overly constraints its applicability. Right now, the reduce/4 function takes the following arguments:

- `X0` the expression to be reduced
- `Rho` the variable bindings in the top-level context
- `Gamma` the functions which are defined
- `Cwd` the directory name from which to resolve input files

The reduce/4 function implicitly assumes that a corresponding CRE service is registered under `cre` and starts to communicate with it, when it sees a foreign function application.

To relax the dependence of the reduce/4 function to a registered service you made two proposals:

1. Each call to reduce starts its own CRE and, therefore, must be provided with the parameters necessary to do so
2. Each call to reduce is given the PID of the CRE, instead of hard-wiring it

Personally, I'd prefer the second option and as it seems you already made the according changes in the code. One thing, I'd probably do different is that I'd take the Runtime argument as the first, instead of the last parameter to reduce/5 so that it is consistent with the submit/3 function.

I'd accept a pull request right away.

**Comment by zampino** [comment]
ja the first option is definitely not optimal!

this is great, thanks for the feedback, I'll update the signature as you suggest and open a pull request soon. Cheers.

**Comment by joergen7** [comment]
I think we have done this. It's part of 2.2.1. I'll close the issue.
